#ifndef onsite_h
#define onsite_h

#include "model.h"

void ONSITE_SXSX_SZBASIS_HB(int spin, CRS1 *M, double coeef);
void ONSITE_SZ_SZBASIS_HB(int spin, CRS1 *M, double coeef);
void ONSITE_SP_SZBASIS_HB(int spin, CRS1 *M, double coeef);
void ONSITE_SZSZ_SZBASIS_HB(int spin, CRS1 *M, double coeef);
void ONSITE_SX_SZBASIS_HB(int spin, CRS1 *M, double coeef);
void ONSITE_SM_SZBASIS_HB(int spin, CRS1 *M, double coeef);
void ONSITE_SZL_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXL_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZLSZL_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXLSXL_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SPL_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SML_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZC_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXC_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZCSZC_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXCSXC_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SPC_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SMC_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CUP_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CDOWN_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CUP_DAGGER_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CDOWN_DAGGER_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SCSL_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_DO_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NC_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NC_DOWN_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NC_UP_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NB_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NCNC_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZL_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXL_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SPL_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SML_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZLSZL_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXLSXL_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZC_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXC_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZCSZC_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_EVEN_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_ODD_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_EVEN_DAGGER_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_ODD_DAGGER_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SCSL_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NC_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NCNC_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_LSPIN_COMPONENT_SPIN_INV_BASIS_KLM(int num, int spin_loc, CRS1 *M, double coeef);
void ONSITE_LSCC_KLM(int num, int spin_loc, CRS1 *M, double coeef);
void ONSITE_LSC_KLM(int num, int spin_loc, CRS1 *M, double coeef);
void ONSITE_CC_KLM(int num, int spin_loc, CRS1 *M, double coeef);
void ONSITE_C_KLM(int num, int spin_loc, CRS1 *M, double coeef);

int ONSITE_FIND_SITE_ELE_SZBASIS_KLM(int basis, int spin_loc);
int ONSITE_FIND_SITE_SZ_SZBASIS_KLM(int basis, int spin_loc);
int ONSITE_FIND_SITE_PARITY_SPIN_INV_BASIS_KLM(int basis, int spin_loc);
int ONSITE_FIND_SITE_ELE_SPIN_INV_BASIS_KLM(int basis, int spin_loc);
void ONSITE_MAKE_HAM_SPIN_INV_BASIS_KLM(MODEL_1DKLM_TVF *Model, CRS1 *M);
void ONSITE_MAKE_HAM_SZBASIS_KLM(MODEL_1DKLM_VF *Model, CRS1 *M);
void ONSITE_DIAG_SPIN_INV_BASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_DIAG_SZBASIS_KLM(int spin_loc, CRS1 *M, double coeef);
void MAKE_LSC_MAT_BASIS_1DKLM_TVF(int sc_p, SC_MAT_1DKLM_TVF *Sc_Mat, int lspin, int tot_site);
void MAKE_SC_MAT_BASIS_1DKLM_TVF(int sc_p, SC_MAT_1DKLM_TVF *Sc_Mat, int tot_site);
void MAKE_LSC_MAT_BASIS_1DKLM_VF(int sc_sz, SC_MAT_1DKLM_VF *Sc_Mat, int lspin, int tot_site);
void MAKE_SC_MAT_BASIS_1DKLM_VF(int sc_sz, SC_MAT_1DKLM_VF *Sc_Mat, int tot_site);
SC_MAT_1DKLM_TVF *GET_SC_MAT_BASIS_1DKLM_TVF(MODEL_1DKLM_TVF *Model);
SC_MAT_1DKLM_VF *GET_SC_MAT_BASIS_1DKLM_VF(MODEL_1DKLM_VF *Model);
void FREE_SC_MAT_BASIS_1DKLM_TVF(SC_MAT_1DKLM_TVF *Sc_Mat, MODEL_1DKLM_TVF *Model);
void FREE_SC_MAT_BASIS_1DKLM_VF(SC_MAT_1DKLM_VF *Sc_Mat, MODEL_1DKLM_VF *Model);


SC_MAT_1DTKLM_VF *GET_SC_MAT_BASIS_1DTKLM_VF(MODEL_1DTKLM_VF *Model);
void FREE_SC_MAT_BASIS_1DTKLM_VF(SC_MAT_1DTKLM_VF *Sc_Mat, MODEL_1DTKLM_VF *Model);
void MAKE_SC_MAT_BASIS_1DTKLM_VF(int sc_sz, int ele_1, int ele_2, SC_MAT_1DTKLM_VF *Sc_Mat, MODEL_1DTKLM_VF *Model);
void ONSITE_CCSL_TKLM(int num, int spin_loc, CRS1 *M, double coeef);
void ONSITE_SL_TKLM(int num, int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZL_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXL_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SC_1SL_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SC_2SL_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZC_1_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZC_2_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXC_1_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SXC_2_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SZLSZL_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NC_1_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_NC_2_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SPL_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_SML_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CUP_1_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CDOWN_1_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CUP_1_DAGGER_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CDOWN_1_DAGGER_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CUP_2_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CDOWN_2_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CUP_2_DAGGER_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_CDOWN_2_DAGGER_SZBASIS_TKLM(int spin_loc, CRS1 *M, double coeef);
void ONSITE_MAKE_HAM_SZBASIS_TKLM(MODEL_1DTKLM_VF *Model, CRS1 *M);
int ONSITE_FIND_SITE_SZ_SZBASIS_TKLM(int basis, int spin_loc);
int ONSITE_FIND_SITE_ELE_1_SZBASIS_TKLM(int basis, int spin_loc);
int ONSITE_FIND_SITE_ELE_2_SZBASIS_TKLM(int basis, int spin_loc);

void ONSITE_CUP_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_CUP_DAGGER_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_CDOWN_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_CDOWN_DAGGER_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_NC_UP_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_NC_DOWN_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_NC_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_SZC_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_SXC_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_NC_UP_NC_DOWN_SZBASIS_HUBBARD(CRS1 *M, double coeef);
void ONSITE_MAKE_HAM_SZBASIS_HUBBARD(MODEL_1DHUBBARD_VF *Model, CRS1 *M);
void ONSITE_CC_HUBBARD(CRS1 *M, double coeef);
void ONSITE_C_HUBBARD(int num, CRS1 *M, double coeef);
int  ONSITE_FIND_SITE_SZ_SZBASIS_HUBBARD(int basis);
int  ONSITE_FIND_SITE_ELE_SZBASIS_HUBBARD(int basis);
SC_MAT_1DHUBBARD_VF *GET_SC_MAT_BASIS_1DHUBBARD_VF(MODEL_1DHUBBARD_VF *Model);
void MAKE_SC_MAT_BASIS_1DHUBBARD_VF(int sc_sz, SC_MAT_1DHUBBARD_VF *Sc_Mat, int tot_site);
void FREE_SC_MAT_BASIS_1DHUBBARD_VF(SC_MAT_1DHUBBARD_VF *Sc_Mat, MODEL_1DHUBBARD_VF *Model);
#endif /* onsite_h */
